# Generated by Django 6.0.4 on 2026-04-21 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderTime',
            new_name='OrderItem',
        ),
    ]
